TT#84224 Replace npm by yarn
The intention here is to replace NPM entirely. The reason is that we did have a lot of trouble with it and were surprised by a recent regression. The behavior of "npm install" changed significantly and caused altered dependencies during build process.

It is an experimental change to see if YARN is able to help to improve the dependency situation with Javascript based projects. The YARN-cli can be seen as full replacement for NPM and is the most reliable alternative for production systems. We do not lose significant functionality with it.

The test phase is supposed to take two release cycles and include at least one or more dependency change to see the behavior. After a successful test we would switch all other Javascript projects step by step to yarn. The next project would be ngcp-csc-ui.

Change-Id: Idc038286b2e406cc3f6d656f21caf687f07ed3ca

diff --git a/t/run_admin_ui b/t/run_admin_ui
--- a/t/run_admin_ui
+++ b/t/run_admin_ui
@@ -8,7 +8,7 @@ cd /code
 echo "Checking NGCP environment configuration"
 ngcp_address="$1"
 if [ -z "${ngcp_address}" ] ; then
-  echo "ERROR: Missing NGCP address, please check the script parameters. Aborting."
+  echo "ERROR: Missing NGCP address, please check the script parameters. Aborting." >&2
   exit 1
 fi
 echo "Found NGCP address '${ngcp_address}', processing further..."
@@ -17,7 +17,7 @@ quasar_config="src/config/app.js"
 default_quasar_config="src/config/app.prod.js"
 if [ ! -f "${quasar_config}" ]; then
   if [ ! -f "${default_quasar_config}" ]; then
-    echo "ERROR: missing default quasar config '${default_quasar_config}'. Aborting."
+    echo "ERROR: missing default quasar config '${default_quasar_config}'. Aborting." >&2
     exit 1
   fi
 
@@ -34,19 +34,19 @@ if ! grep -q "${ngcp_address}" "${quasar_config}" >/dev/null 2>&1; then
 fi
 echo "Quasar config '${quasar_config}' is OK."
 
-echo "JFYI, important components versions:"
+echo "Component versions"
 echo -n "node --version : " && node --version
-echo -n "npm  --version : " && npm --version
+echo -n "yarn  --version : " && yarnpkg --version
 
-echo "Configuring Vue.js/Quasar dev environment, running 'npm ci'..."
-if ! npm ci ; then
-  echo "ERROR: cannot install all npm dependencies. Aborting."
+echo "Configuring Vue.js/Quasar dev environment"
+if ! yarnpkg install ; then
+  echo "ERROR: cannot install all dependencies. Aborting." >&2
   exit 1
 fi
 
-echo "Starting Quasar dev environment, running 'npm run dev'..."
-if ! npm run dev; then
-  echo "ERROR: cannot run quasar dev environment. Aborting."
+echo "Starting Quasar dev environment"
+if ! yarnpkg run dev; then
+  echo "ERROR: cannot run quasar dev environment. Aborting." >&2
   exit 1
 fi
 
